//
//  ListBreedsImagesModels.swift
//  DogBreeds
//
//  Created by Nisum on 6/12/18.
//  Copyright (c) 2018 Nisum. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum ListBreedsImages
{
  // MARK: Use cases
  
  enum FetchImagesURLs
  {
    struct Request
    {
    }
    struct Response
    {
        var breedImagesURLs: [String]
        var error: BreedsStoreError?
    }
    struct ViewModel
    {
        var imagesURLs: [String]
        var errorMessage: String?
    }
  }
}
