//
//  ListBreedsImagesInteractor.swift
//  DogBreeds
//
//  Created by Nisum on 6/12/18.
//  Copyright (c) 2018 Nisum. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ListBreedsImagesBusinessLogic
{
    func fetchBreedImagesURLs(request: ListBreedsImages.FetchImagesURLs.Request)
}

protocol ListBreedsImagesDataStore
{
    var breed: Breed? { get set }
    var breedImagesURLs: [String]? {get}
}

class ListBreedsImagesInteractor: ListBreedsImagesBusinessLogic, ListBreedsImagesDataStore
{
    var presenter: ListBreedsImagesPresentationLogic?
    var worker = ListBreedsImagesWorker(breedsStore: BreedsAPI())
    var breed: Breed?
    var breedImagesURLs: [String]?
    
    func fetchBreedImagesURLs(request: ListBreedsImages.FetchImagesURLs.Request) {
        worker.fetchBreedImageURLs(breedName: (breed?.name)!) { [weak self] (breedImagesURLs, error) in
            guard let weakSelf = self else {
                return
            }
            if error == nil {
                weakSelf.breedImagesURLs = []
            } else {
                weakSelf.breedImagesURLs = breedImagesURLs
            }
            let response = ListBreedsImages.FetchImagesURLs.Response(breedImagesURLs: breedImagesURLs, error: error)
            weakSelf.presenter?.storageBreedImagesURLs(response: response)
        }
    }
}

