//
//  ListBreedsImagesPresenter.swift
//  DogBreeds
//
//  Created by Nisum on 6/12/18.
//  Copyright (c) 2018 Nisum. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ListBreedsImagesPresentationLogic
{
    func storageBreedImagesURLs(response: ListBreedsImages.FetchImagesURLs.Response)
    func displayLoadingHud()
    func dismissLoadingHud()
    func displayError(error: BreedsStoreError)
}

class ListBreedsImagesPresenter: ListBreedsImagesPresentationLogic
{
    weak var viewController: ListBreedsImagesDisplayLogic?
    
    func storageBreedImagesURLs(response: ListBreedsImages.FetchImagesURLs.Response) {
        var viewModel: ListBreedsImages.FetchImagesURLs.ViewModel!
        viewModel = ListBreedsImages.FetchImagesURLs.ViewModel(imagesURLs: response.breedImagesURLs)
        viewController?.storageBreedImagesURLs(response: viewModel)
    }
    
    func displayLoadingHud() {
        viewController?.displayLoadingHud()
    }
    
    func dismissLoadingHud() {
        viewController?.dismissLoadingHud()
    }
    
    func displayError(error: BreedsStoreError) {
        viewController?.displayError(error: error.localizedDescription)
    }
}

