//
//  ListBreedsImagesWorker.swift
//  DogBreeds
//
//  Created by Nisum on 6/12/18.
//  Copyright (c) 2018 Nisum. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class ListBreedsImagesWorker
{
    var breedsStore: BreedsStoreProtocol
    
    init(breedsStore: BreedsStoreProtocol)
    {
        self.breedsStore = breedsStore
    }
    
    func fetchBreedImageURLs(breedName: String, completionHandler: @escaping ([String], BreedsStoreError?) -> Void)
    {
        breedsStore.fetchBredImagesURLs(forBreed: breedName) { (breedImagesURLs, error) in
            DispatchQueue.main.async {
                completionHandler(breedImagesURLs, error)
            }
        }
    }
}
