//
//  ListBreedsRouter.swift
//  DogBreeds
//
//  Created by Nisum on 6/12/18.
//  Copyright (c) 2018 Nisum. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol ListBreedsRoutingLogic
{
    func routeToBreedImagesList(segue: UIStoryboardSegue?)
}

protocol ListBreedsDataPassing
{
    var dataStore: ListBreedsDataStore? { get }
}

class ListBreedsRouter: NSObject, ListBreedsRoutingLogic, ListBreedsDataPassing
{
    weak var viewController: ListBreedsViewController?
    var dataStore: ListBreedsDataStore?
    
    // MARK: Routing
    
    func routeToBreedImagesList(segue: UIStoryboardSegue?)
    {
        if let segue = segue {
            let destinationVC = segue.destination as! ListBreedsImagesViewController
            var destinationDS = destinationVC.router!.dataStore!
            passDataToBreedImagesList(source: dataStore!, destination: &destinationDS)
        } /*else {
         let storyboard = UIStoryboard(name: "Main", bundle: nil)
         let destinationVC = storyboard.instantiateViewController(withIdentifier: "ListBreedsImagesViewController") as! SomewhereViewController
         var destinationDS = destinationVC.router!.dataStore!
         passDataToBreedImagesList(source: dataStore!, destination: &destinationDS)
         navigateToBreedImagesList(source: viewController!, destination: destinationVC)
         }*/
    }
    
    // MARK: Navigation
    
    func navigateToBreedImagesList(source: ListBreedsViewController, destination: ListBreedsImagesViewController)
    {
        source.show(destination, sender: nil)
    }
    
    // MARK: Passing data
    
    func passDataToBreedImagesList(source: ListBreedsDataStore, destination: inout ListBreedsImagesDataStore)
    {
        let selectedRow = viewController?.tableView.indexPathForSelectedRow?.row
        destination.breed = source.breeds?[selectedRow!]
    }
}

