//
//  ListBreedsModels.swift
//  DogBreeds
//
//  Created by Nisum on 6/12/18.
//  Copyright (c) 2018 Nisum. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum ListBreeds
{
  // MARK: Use cases
  
  enum FetchBreeds
  {
    struct Request
    {
    }
    struct Response
    {
        var breeds: [Breed]
        var error: BreedsStoreError?
    }
    struct ViewModel
    {
        struct DisplayedBreed {
            var name: String
        }
        var displayedBreeds: [DisplayedBreed]
        var errorMessage: String?
    }
  }
}
