//
//  ListBreedsWorker.swift
//  DogBreeds
//
//  Created by Nisum on 6/12/18.
//  Copyright (c) 2018 Nisum. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import Foundation

class ListBreedsWorker
{
    var breedsStore: BreedsStoreProtocol
    
    init(breedsStore: BreedsStoreProtocol)
    {
        self.breedsStore = breedsStore
    }
    
    func fetchBreeds(completionHandler: @escaping ([Breed], BreedsStoreError?) -> Void)
    {
        breedsStore.fetchBreeds { (breeds, error) in
            completionHandler(breeds, error)
        }
    }
}
