//
//  ListBreedsPresenter.swift
//  DogBreeds
//
//  Created by Nisum on 6/12/18.
//  Copyright (c) 2018 Nisum. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol ListBreedsPresentationLogic
{
    func presentFetchedBreeds(response: ListBreeds.FetchBreeds.Response)
}

class ListBreedsPresenter: ListBreedsPresentationLogic
{
  weak var viewController: ListBreedsDisplayLogic?

    func presentFetchedBreeds(response: ListBreeds.FetchBreeds.Response) {
        var viewModel: ListBreeds.FetchBreeds.ViewModel!
        if response.error != nil {
            viewModel = ListBreeds.FetchBreeds.ViewModel(displayedBreeds: [], errorMessage: response.error?.localizedDescription)
        } else {
            var displayedBreeds: [ListBreeds.FetchBreeds.ViewModel.DisplayedBreed] = []
            
            for breed in response.breeds {
                let displayedBreed = ListBreeds.FetchBreeds.ViewModel.DisplayedBreed(name: breed.name)
                displayedBreeds.append(displayedBreed)
            }
            viewModel = ListBreeds.FetchBreeds.ViewModel(displayedBreeds: displayedBreeds, errorMessage: nil)
        }
        viewController?.displayFetchedBreeds(viewModel: viewModel)
    }
}
