//
//  ListBreedsImagesViewControllerTests.swift
//  DogBreeds
//
//  Created by Nisum on 6/13/18.
//  Copyright (c) 2018 Nisum. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

@testable import DogBreeds
import XCTest

class ListBreedsImagesViewControllerTests: XCTestCase
{
    // MARK: - Subject under test
    
    var sut: ListBreedsImagesViewController!
    var window: UIWindow!
    
    // MARK: - Test lifecycle
    
    override func setUp()
    {
        super.setUp()
        window = UIWindow()
        setupListBreedsImagesViewController()
    }
    
    override func tearDown()
    {
        window = nil
        super.tearDown()
    }
    
    // MARK: - Test setup
    
    func setupListBreedsImagesViewController()
    {
        let bundle = Bundle.main
        let storyboard = UIStoryboard(name: "Main", bundle: bundle)
        sut = storyboard.instantiateViewController(withIdentifier: "ListBreedsImagesViewController") as! ListBreedsImagesViewController
    }
    
    func loadView()
    {
        window.addSubview(sut.view)
        RunLoop.current.run(until: Date())
    }
    
    // MARK: - Test doubles
    
    class ListBreedsImagesBusinessLogicSpy: ListBreedsImagesBusinessLogic
    {
        var breedURLS: [String]?
        
        // MARK: Method call expectations
        
        var fetchBreedImagesURLsCalled = false
        
        // MARK: Spied methods
        
        func fetchBreedImagesURLs(request: ListBreedsImages.FetchImagesURLs.Request) {
            fetchBreedImagesURLsCalled = true
        }
    }
    
    class TableViewSpy: UITableView
    {
        // MARK: Method call expectations
        
        var reloadDataCalled = false
        
        // MARK: Spied methods
        
        override func reloadData()
        {
            reloadDataCalled = true
        }
    }
    
    // MARK: Tests
    
    func testShouldFetchBreedsWhenViewIsLoaded()
    {
        // Given
        let listBreedsBusinessLogicSpy = ListBreedsImagesBusinessLogicSpy()
        sut.interactor = listBreedsBusinessLogicSpy
        
        // When
        loadView()
        
        // Then
        XCTAssertTrue(listBreedsBusinessLogicSpy.fetchBreedImagesURLsCalled, "viewDidLoad() should ask the interactor to fetch breeds")
    }
    
    func testShouldDisplayBreeds()
    {
        // Given
        let tableViewSpy = TableViewSpy()
        sut.tableView = tableViewSpy
        
        // When
        let imageURLs = ["https://images.dog.ceo/breeds/spaniel-blenheim/n02086646_1014.jpg"]
        let viewModel = ListBreedsImages.FetchImagesURLs.ViewModel(imagesURLs: imageURLs)
        sut.storageBreedImagesURLs(response: viewModel)
        
        // Then
        XCTAssert(tableViewSpy.reloadDataCalled, "Displaying fetched breeds should reload the table view")
    }
}

